[[language]]
name = 'python'
language-servers = ['basedpyright', 'ruff']
auto-format = true

[[language]]
name = 'javascript'
formatter = { command = 'prettier', args = [
  '--parser',
  'typescript',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'jsx'
formatter = { command = 'prettier', args = [
  '--parser',
  'typescript',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'css'
formatter = { command = 'prettier', args = [
  '--parser',
  'css',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'json'
formatter = { command = 'prettier', args = [
  '--parser',
  'json',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'markdown'
formatter = { command = 'prettier', args = [
  '--parser',
  'markdown',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'html'
formatter = { command = 'prettier', args = [
  '--parser',
  'html',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'typescript'
formatter = { command = 'prettier', args = [
  '--parser',
  'typescript',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'tsx'
formatter = { command = 'prettier', args = [
  '--parser',
  'typescript',
  '--stdin-filepath',
  '%{buffer_name}',
] }
language-servers = ['typescript-language-server', 'tailwindcss-ls']
auto-format = true

[[language]]
name = 'graphql'
formatter = { command = 'prettier', args = [
  '--parser',
  'graphql',
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'clojure'
formatter = { command = 'cljstyle', args = ['pipe'] }
auto-format = true

[[language]]
name = 'java'
formatter = { command = 'google-java-format', args = ['-'] }
auto-format = true

[language-server.rust-analyzer.config.check]
command = 'clippy'

[[language]]
name = 'toml'
auto-format = true

[[language]]
name = 'ghostty'
language-servers = ['ghostty-ls']

[language-server.ghostty-ls]
command = 'ghostty-ls'

[language-server.phpactor]
command = 'phpactor.phar'
args = ['language-server']

[[language]]
name = 'php'
language-servers = ['phpactor']
auto-format = true

[[language]]
name = 'hurl'
auto-format = true

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierEnding = 'minimal'
importModuleSpecifierPreference = 'non-relative'
